package FACEBOOK_API

const FACEBOOK_REQUEST_API_VERSION = "GOAPP_ENV_FACEBOOK_REQUEST_API_VERSION"
const FACEBOOK_PROFILE_FIELDS = "GOAPP_ENV_FACEBOOK_PROFILE_FIELDS"
const FACEBOOK_CLIENT_ID = "GOAPP_ENV_FACEBOOK_CLIENT_ID"
const FACEBOOK_CLIENT_SECRET = "GOAPP_ENV_FACEBOOK_CLIENT_SECRET"
